### PR TITLE
[Hazard System + Wheel of Destiny] Converting to New Canary

### PR DESCRIPTION
**Pull request by Underewarrr**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by paczielny** [comment]
error trying to compile :/
error

**Comment by Underewarrr** [comment]
> error trying to compile :/ error

Sure, at momment im fixing some errors in this conversion.

At moment i got hazard working, i wil create two new separeted banch for hazard and wheel of destiny.

Soon this branchs will receive an pull request.

**Comment by paczielny** [comment]
> 

thanks Rafhael  you are the best

**Comment by Underewarrr** [comment]
> > 
> 
> thanks Rafhael you are the best

Hello! For test purpose, you can use this server base :
https://github.com/thetibiaking/canary-mixed

**Comment by paczielny** [comment]
> 

image

Help me bro :(
I don't know why I get this error

**Comment by Underewarrr** [comment]
> > 
> 
> image
> 
> Help me bro :( I don't know why I get this error

If you have changed something you will need to refac this part.

This seen a problem with bad complexity in c++.

If you trying to use the [canary-mixed](https://github.com/thetibiaking/canary-mixed), try to use the linux-release, avaliable in releases.

- My Bad i added the linux-release.

If you dont have edited nothing then this errors maybe happen in the compiler in windows, i will take a close look in that.

**Comment by paczielny** [comment]
> > > 
> > 
> > thanks Rafhael you are the best
> 
> Hello! For test purpose, you can use this server base :
> https://github.com/thetibiaking/canary-mixed

Hello @Underewarrr some database in windows?
I dont know how yo compile un Linux 😕

**Comment by Underewarrr** [comment]
> > > > 
> > > 
> > > 
> > > thanks Rafhael you are the best
> > 
> > 
> > Hello! For test purpose, you can use this server base :
> > https://github.com/thetibiaking/canary-mixed
> 
> Hello @Underewarrr some database in windows? I dont know how yo compile un Linux 😕

Hello! You can compile this following this steps
https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29

**Pull request closed without merging**
